
BLENDER="C:\Program Files\Blender Foundation\Blender 2.90\blender.exe"
DIST=../dist


$(DIST)/city.scene : city.blend export-scene.py
    $(BLENDER) --background --python export-scene.py -- "city.blend:Main" "$(DIST)/city.scene"

$(DIST)/city.pnct : city.blend export-meshes.py
    $(BLENDER) --background --python export-meshes.py -- "city.blend:Main" "$(DIST)/city.pnct"
